### ISSUE TITLE
Time to release ?

### ISSUE THREAD

**Issue by palpaga** [prometheus-community/PushProx#105]
Hi,
Would it be possible to have an official release? or push a latest version on quay/docker hub (prom ?)?
I would like to integrate pushprox in my GKE monitoring cluster (prometheus stack) and i don't want to add build stage in my CI only for pushprox-client and proxy
Ty,

**Comment by SuperQ** [comment]
Yes, it's probably worth doing some updates and publishing a new release.

**Comment by courageJ** [comment]
+1

**Comment by ashish1099** [comment]
+1

**Comment by thejhh** [comment]
Last release was 2009. Would appreciate one :)

**Comment by palpaga** [comment]
Thanks ! https://github.com/prometheus-community/PushProx/releases/tag/v0.2.0
I closed the issue
