### ISSUE TITLE
server returned HTTP status 502 Bad Gateway

### ISSUE THREAD

**Issue by mlrz00** [prometheus-community/PushProx#108]
Hi guys,
After setup the proxy and the client, i ran them and it works as expected but i don' know why i am getting "server returned HTTP status 502 Bad Gateway".
Thanks in advance

**Comment by Lamaspanzer** [comment]
Hi,
Do you use a reverse proxy ?

**Comment by Louriz0** [comment]
Hi @Lamaspanzer no i don't use a reverse proxy in front of pushprox-proxy
