### ISSUE TITLE
Scraping more then one exporter.

### ISSUE THREAD

**Issue by ashish1099** [prometheus-community/PushProx#116]
I have been struggling to come up with a way to work with multiple exporter, but can not figure out how.

I can scrape the metrics from the client, based on the config in prometheus.yaml file.
But then I have to add the port no of node_exporter (manually) so prom can ask the pushprox proxy and goes to pushprox client and comes back with the metrics from the client node.

Now when I have couple of more exporters running on the client side, how do I configure prometheus to automatically figure out the port of the exporter which is running on the client side. so I dont have to enter the port no in  the config file manually.

I'm not sure if this is possible or not.

Whats with the label, I see its always empty, how can I add labels 

```
[{"targets":["0532c74f7e43"],"labels":null},{"targets":["dev-node-exporter"],"labels":null}]
```

Thanks.

**Comment by scythargon** [comment]
+1 here

**Comment by GSergeevich** [comment]
+1 a proxy-client within the network can scrap many targets, and it would be useful if you only need to run one such client on the network

**Comment by anolting** [comment]
+1

**Comment by ashish1099** [comment]
> +1 @ashish1099, would not it make sense to create a separate issue for the label problem?

I agree

**Comment by ashish1099** [comment]
We ended up fixing this in a different way.

We are using puppet for config mgmt, and simply created a puppet resoucrce which goes and run on all the client and then simply do an api request on puppetdb and get the list of nodes which the specific resources and based on that we generate the required json file with the required format.
