### ISSUE TITLE
compression support?

### ISSUE THREAD

**Issue by belm0** [prometheus-community/PushProx#69]
Is PushProx supporting gzip Content-Encoding, at least for the scrape request between the proxy and client?

Assuming so, it's perhaps worth noting in the README.

**Comment by brian-brazil** [comment]
I don't think that's the sort of detail that'd be documented, we pass on all headers though which would include the ones indicating that Prometheus supports compression.

**Comment by SuperQ** [comment]
I would probably document it like this:

```
PushProx passes all HTTP headers transparently, features like compression and accept encoding are up to the scraping Prometheus server.
```

**Comment by belm0** [comment]
Do you mean that the headers will be passed all the way to the target, and so it's up to the target to implement gzip or whatever on `/metrics` GET?

**Comment by brian-brazil** [comment]
Yes. This is a reasonably dumb proxy.

**Comment by SuperQ** [comment]
This was fixed (documented) in https://github.com/prometheus-community/PushProx/pull/71.
