### ISSUE TITLE
Is there a possibility to build the client on Windows?

### ISSUE THREAD

**Issue by spprod35** [prometheus-community/PushProx#75]
Hello,

I want to know if it is possible to build the client for a Windows Server target?

I have a server stuck behind a NAT and I would like to use pushProx to recover metrics.
I do not know GO very well, I understand that it was possible.

Thank you all

**Comment by SuperQ** [comment]
Yes, Go can compile on Windows.

You can also build a Windows binary from Linux.

```
GOOS=windows make build
```

**Comment by spprod35** [comment]
I tried this in the WSL debian shell : 

`
git clone https://github.com/robustperception/pushprox.git
cd pushprox
GOOS=windows
make build
`

The compilation is going well, however the binary does not run on windows, even by changing the exetension to ".exe"

**Comment by MountainAndSea** [comment]
I have build this for windows.
we need install MinGW and go on windows , and use mingw32-make.exe to make build.
```
git clone https://github.com/robustperception/pushprox.git
cd pushprox
/c/MinGW/bin/mingw32-make.exe build
```

**Comment by SuperQ** [comment]
@spprod35 You either need to to put `GOOS=windows make build` on the same line, or "export" the variable for the setting to be passed into make. There is no need to rename the file, the build will do this correctly. This is standard environment variable scoping on Linux, something required if you use WSL as your build environment.

```
$ export GOOS=windows
$ make build
>> building binaries
GO111MODULE=on /home/ben/go/bin/promu build --prefix /home/ben/src/RobustPerception/PushProx 
 >   pushprox-client.exe
 >   pushprox-proxy.exe
```

**Comment by SuperQ** [comment]
We now have pre-built binaries in the release process.
