### ISSUE TITLE
How to integration with prometheus operator

### ISSUE THREAD

**Issue by Alanthur** [prometheus-community/PushProx#96]
Hi,I use prometheus operator,but I do not know how to integration with pushProx?
How do I configure the prometheus operator to integration with pushProx?
Any help is appreciate

**Comment by grzesuav** [comment]
how you would like to integrate ? IMO it would be enough to set it up as pod in k8s and set `ServiceMonitor` to scrape from pushprox

**Comment by SuperQ** [comment]
There's no need for PushProxy in Kuberentes. Prometheus inside the cluster can reach services directly.
